spring:
  application:
    name: GameFestivalDemo
  datasource:
    url: jdbc:postgresql://ep-dark-smoke-ansml829.c-6.us-east-1.aws.neon.tech:5432/gamefestival
    username: neondb_owner
    password: npg_Juc0w5zOqKeU
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /gamefestival/demo/api
    port: 8081
